import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// cricket-live — turns free, factual live-score data into original Telugu radio
// commentary. Score facts (runs/wickets/overs) are not copyrightable; the
// commentary is generated by Gemini, so this is our own content — no broadcast
// audio is reproduced.
//
// Env:
//   CRICKET_API_KEY  — cricketdata.org (cricapi) free tier. Without it, the
//                      endpoint reports no live match (card stays hidden).
//   GEMINI_API_KEY   — already configured (shared with the other functions).
//
// ?mock=1 returns commentary for a fixed sample match so the pipeline can be
// verified before a key is set / while no match is live.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers":
    "authorization, apikey, content-type, x-client-info",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json",
      // Live scores move fast, but respect the free-tier quota — 60s edge cache.
      "Cache-Control": "public, max-age=60",
    },
  });
}

interface MatchFacts {
  name: string;
  teams: string[];
  matchType: string;
  status: string;
  scoreText: string;
}

// Build a compact, factual one-liner for Gemini from a cricapi match object.
function factsFrom(m: Record<string, unknown>): MatchFacts {
  const teams = (m.teams as string[]) ?? [];
  const scores = (m.score as Array<Record<string, unknown>>) ?? [];
  const scoreText = scores
    .map((s) =>
      `${s.inning ?? ""}: ${s.r ?? 0}/${s.w ?? 0} (${s.o ?? 0} ov)`.trim()
    )
    .join("  ");
  return {
    name: (m.name as string) ?? "",
    teams,
    matchType: (m.matchType as string) ?? "",
    status: (m.status as string) ?? "",
    scoreText,
  };
}

async function commentary(facts: MatchFacts, geminiKey: string): Promise<string> {
  const prompt =
    `You are an energetic Telugu cricket radio commentator. Using ONLY these ` +
    `factual live-match details, write 2 short, exciting sentences of original ` +
    `commentary in TELUGU SCRIPT ONLY (no English words, no romanisation). Do ` +
    `not invent events not implied by the facts.\n\n` +
    `Match: ${facts.name}\nType: ${facts.matchType}\nStatus: ${facts.status}\n` +
    `Score: ${facts.scoreText}\n\nOutput only the Telugu commentary.`;
  const r = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${geminiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.9,
          maxOutputTokens: 300,
          thinkingConfig: { thinkingBudget: 0 },
        },
      }),
      signal: AbortSignal.timeout(40_000),
    },
  );
  if (!r.ok) throw new Error(`Gemini HTTP ${r.status}`);
  const data = await r.json() as {
    candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }>;
  };
  return (data.candidates?.[0]?.content?.parts ?? [])
    .map((p) => p.text ?? "").join("").trim();
}

const MOCK: MatchFacts = {
  name: "India vs Australia, 2nd T20I",
  teams: ["India", "Australia"],
  matchType: "T20",
  status: "India need 47 runs in 22 balls",
  scoreText: "India: 234/4 (18.2 ov)",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  try {
    const GEMINI_KEY = Deno.env.get("GEMINI_API_KEY");
    if (!GEMINI_KEY) {
      return json({ error: "config_missing", message: "GEMINI_API_KEY" }, 500);
    }
    const url = new URL(req.url);
    const mock = url.searchParams.get("mock") === "1";

    let facts: MatchFacts;
    if (mock) {
      facts = MOCK;
    } else {
      const KEY = Deno.env.get("CRICKET_API_KEY");
      if (!KEY) return json({ ok: true, live: false, reason: "no_api_key" });
      const resp = await fetch(
        `https://api.cricapi.com/v1/currentMatches?apikey=${KEY}&offset=0`,
        { signal: AbortSignal.timeout(15_000) },
      );
      if (!resp.ok) {
        return json({ ok: true, live: false, reason: `upstream_${resp.status}` });
      }
      const body = await resp.json() as { data?: Array<Record<string, unknown>> };
      const live = (body.data ?? []).find(
        (m) => m.matchStarted === true && m.matchEnded === false,
      );
      if (!live) return json({ ok: true, live: false, reason: "no_live_match" });
      facts = factsFrom(live);
    }

    let text = "";
    try {
      text = await commentary(facts, GEMINI_KEY);
    } catch (e) {
      console.warn("[cricket-live] commentary failed:", (e as Error).message);
    }

    return json({
      ok: true,
      live: true,
      mock,
      name: facts.name,
      teams: facts.teams,
      status: facts.status,
      scoreText: facts.scoreText,
      commentary: text,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("[cricket-live]", err);
    return json({ error: "cricket_failed", message }, 500);
  }
});
